---
title: "Quality control of bulk ATAC-sequencing of non-naive CD8s from AbATE"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(dplyr)
library(tidyr)
library(readr)
library(readxl)
library(stringr)
library(ggplot2)
library(ggthemes)
library(ggbeeswarm)
library(viridis)
library(RColorBrewer)
library(ggrepel)
library(ggpubr)
library(plotly)
library(kableExtra)
library(ATACseqQC)
library(GenomicAlignments)
library(DiffBind)
library(EnsDb.Hsapiens.v86)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(org.Hs.eg.db)
library(ChIPpeakAnno)
library(SummarizedExperiment)
library(edgeR)
library(limma)
library(statmod)

`%notin%` <- Negate(`%in%`)

select   <- dplyr::select
rename   <- dplyr::rename
filter   <- dplyr::filter
distinct <- dplyr::distinct
mutate   <- dplyr::mutate

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

pcutoff = 0.1
logPcutoff = -log10(pcutoff)
logFCcutoff = 0

setwd("/Users/tybottorff/git/Bottorff_CD127_2026/ABATE_BULK_ATAC/")

```

# Read in metadata, set up colors

```{r}

design <- read.csv("./saved_data/metadata_2.csv") %>%
  dplyr::mutate(donorId = as.character(donorId))
num_sort <- length(unique(design$sort))
num_donorId <- length(unique(design$donorId))
num_responder <- length(unique(design$responder))
palette_sort <- viridis(num_sort)
palette_donorId <- viridis(num_donorId)
palette_responder <- viridis(num_responder)
colors.sort <- palette_sort[as.numeric(factor(unique(design$sort)))]
colors.donorId <- palette_donorId[as.numeric(factor(unique(design$donorId)))]
colors.responder <- palette_responder[as.numeric(factor(unique(design$responder)))]
names(colors.sort) <- unique(design$sort)
names(colors.donorId) <- unique(design$donorId)
names(colors.responder) <- unique(design$responder)

```

# Setup file paths

```{r}

# download ATACseq raw data files from Box into ./raw_data
fragmentFiles <- list.files(file.path("./raw_data", "insertSizes"), full.names = TRUE)
names(fragmentFiles) <- str_extract(fragmentFiles, "lib[0-9]+")
alignmentFiles <- list.files(file.path("./raw_data", "merged_alignments"), full.names = TRUE, pattern = "merged_lib.*\\.bam$")
names(alignmentFiles) <- str_extract(alignmentFiles, "lib[0-9]+")
peakFiles <- list.files(file.path("./raw_data", "merged_peaks"), full.names = TRUE, pattern = "lib.*\\.narrowPeak$")
names(peakFiles) <- str_extract(peakFiles, "lib[0-9]+")
fastqFiles <- list.files(file.path("./raw_data", "inputFastqs"), full.names = TRUE, pattern = "fastq\\.gz$")
names(fastqFiles) <- paste(str_extract(fastqFiles, "lib[0-9]+"), str_extract(fastqFiles, "R[0-9]+"), sep = "_")
for (i in seq_len(nrow(design))) {
  libid <- design$libid[i]
  design$bamFile[i] <- alignmentFiles[libid]
  design$fragmentFile[i] <- fragmentFiles[libid]
  design$peakFiles[i] <- peakFiles[libid]
}

```

# Perform QC

```{r}

# transcription start site enrichment
calculateCoverage = function(bamfile, ref) {
  distanceToTSS = -1500:1500
  coverage_ <- regionPlot(bamFile = bamfile, 
                          testRanges = ref, style = "point", 
                          format = "bam", paired = TRUE,
                          minFragmentLength = 0, 
                          maxFragmentLength = 500, 
                          normalize = "RPM")
  # sum coverage across all regions
  coverage = as.vector(colSums(coverage_@assays@data@listData[[1]]))
  # normalize coverage
  coverage = coverage/min(coverage)
  coverage = data.frame(distanceToTSS, coverage)
  colnames(coverage) <- c("distanceToTSS", "aggregateTSSscore")
  return(coverage)
}
TSSs <- resize(genes(TxDb.Hsapiens.UCSC.hg38.knownGene), fix = "start", 1)
seqlevelsStyle(TSSs) <- "NCBI"
fragmentDistributionsFile <- "./saved_data/TSS_coverage.Rdata"
# If the data file exists, load it
if (file.exists(fragmentDistributionsFile)) {
  load(fragmentDistributionsFile)
} else {
    TSScoverage = c()
  for (i in 1:1:nrow(design)) {
    if (!is.na(design$bamFile[i])) {
      TSScoverage_ = calculateCoverage(design$bamFile[i], TSSs)
      TSScoverage_$libid = design$libid[i]
      
      TSScoverage = rbind(TSScoverage, TSScoverage_)
    }
  }
  cat(sprintf("Saving datafile...\n"))
  save(TSScoverage,
       file = pathToDataFile)
}
TSScoverage = merge(TSScoverage, 
                    dplyr::select(design, libid, sort, donorId, responder),
                    by = c("libid"))
TSSePlot  <- TSScoverage %>%
  ggplot(aes(x = distanceToTSS,
             y = aggregateTSSscore,
             group = libid,
             color = donorId))+
  geom_line() +
  scale_color_manual(values = colors.donorId) +
  labs(x = "distance to TSS (bp)",
       y = "aggregate, normalized TSS score", color = "Donor ID") + 
  theme_bw() +
  theme(legend.position="right") + 
  theme(legend.direction='vertical') + 
  facet_wrap(~ sort + responder, labeller = labeller(responder = function(variable) paste("Responder: ", variable)), ncol = 5, scales="fixed") +
  geom_hline(yintercept = 5, linetype = 2) + 
  geom_hline(yintercept = 7, linetype = 3, color = "grey")
plot(TSSePlot)
ggsave("./figures/TSSe_plot.pdf", plot = TSSePlot, height = 8,  width = 12)
# read counts and alignment
# cutoffs from encode
alignCut = 80
readCut = 50000000
fixed_names_design <- design %>%
  mutate(sort = case_when(
    sort == "TIGIT+KLRG1+\nCD57+CD127-" ~ "DP CD57+",
    sort == "TIGIT+KLRG1+\nCD57-CD127-PD1+" ~ "DP PD-1+",
    sort == "TIGIT-\nKLRG1-" ~ "DN",
    sort == "TIGIT+KLRG1+\nCD57-CD127+" ~ "DP CD127+",
    sort == "(TIGIT+KLRG1+)-\nCD127+" ~ "non-exhausted\nCD127+"
  ))
# This makes a total read plot
totalReadsPlot = ggplot(fixed_names_design, aes(fill = donorId, y = tophatstats_total_reads/1e6, x = donorId)) + 
    # this y val comes from metrics so I do need that...
    geom_bar(position="stack", stat="identity") +
    labs(x = "Donor ID", y = "total reads (million)", fill = "Donor ID") + 
    scale_fill_manual(values = colors.donorId) +
    theme(legend.position="bottom") + 
    geom_hline(yintercept = readCut/1e6, linetype = 2) +
    theme(legend.direction='horizontal') +
    coord_cartesian(ylim = c(0, 155)) +
    facet_wrap(~ sort + responder, labeller = labeller(responder = function(variable) paste("Responder: ", variable)), ncol = 5, scales="free") +
    theme_bw() +
    theme(axis.text.x = element_blank(), axis.ticks = element_blank(), strip.text = element_text(size = 7))
print(totalReadsPlot)
ggsave("./total_reads.pdf", totalReadsPlot, height = 6, width = 8)
# This makes a total read plot by cell sort
totalReadsPlot_by_sort = ggplot(fixed_names_design, aes(x = sort, y = tophatstats_total_reads/1e6, fill = sort)) +
  geom_boxplot() +
  labs(x = "Sort",
       y = "total reads / 1e6") +
  theme(axis.text.x = element_blank(), axis.ticks = element_blank(), strip.text = element_text(size = 7), legend.position = "bottom")
print(totalReadsPlot_by_sort)
# calculate mean read count/library ~= 119 million
design %>%
  summarize(mean_read_count = mean(tophatstats_total_reads / 1e6),
            sd_read_count = sd(tophatstats_total_reads / 1e6))# %>%
#  print()
# alignment vs. read count (~alignment vs median CV)
gPctAligned <- ggplot(data = design) +
  geom_point(aes(x = tophatstats_total_reads/1e6, 
                 y = pct_aligned,
                 color = donorId, 
                 shape = sort),
                 size = 1.5) + 
  scale_color_manual(values = colors.donorId) +
  labs(x = "total reads / mio", 
       y = "percent alignment", 
       color = "donor",
       shape = "sort")+
  geom_hline(yintercept = alignCut, linetype = 2)+
  geom_vline(xintercept = readCut/1e6, linetype = 2)+
  ylim(c(0,100))+
  xlim(c(0,160))+
  theme_bw() +
  theme(legend.position = "right") + 
  theme(legend.direction=  'vertical')
print(gPctAligned)
ggsave("./figures/total_reads_vs_alignment.pdf", gPctAligned, height = 7, width = 8)
# peak calling
peaksDataFile <- "./saved_data/peaks.Rdata"
readPeaks = function(peakFile, libid, peakCaller) {
    peaks_ = read.table(peakFile, header = FALSE, fill = TRUE)  %>% mutate(width = abs(V3-V2))
    
    if (peakCaller == "seacr") {
       colnames(peaks_)[1:6] = c("chr", "start", "end", "total sign", "max signal", "max signal region")
    } else if (peakCaller == "macs2") {
       colnames(peaks_)[1:10] = c("chr", "start", "end", "name", "score", "strand", "total sign", "pValue", "qValue", "peak")
    }
    peaks_$libid = libid
    return (peaks_)
    }
# If the data file exists, load it
if (file.exists(peaksDataFile)) {
  load(peaksDataFile)
} else {
  macs2Peaks = c()
  for (i in 1:nrow(design)) {
    # step through library
    print(paste0("Reading peaks from ", design$libid[i]))
    # MACS2 full data set
    # get macs2 peaks
    peaks_ = readPeaks(design$peakFiles[i], libid = design$libid[i], peakCaller = "macs2")
    macs2Peaks = rbind(macs2Peaks, peaks_)
  }
  save(macs2Peaks, file = pathToDataFile)
}
macs2Peaks = dplyr::filter(macs2Peaks, chr %in% c(1:23,"X","Y"))
macs2Peaks = merge(macs2Peaks, dplyr::select(design, c("libid", "donorId", "sort", "responder")), by = "libid")
peakSummary = macs2Peaks %>% 
  dplyr::group_by(libid) %>%
  dplyr::summarise(nPeaks = n(), minPeak = min(width), meanPeaks = mean(width), medianPeaks = median(width), maxPeak = max(width))
design = merge(design, peakSummary, by = "libid")
# calculate FRiP (fraction of reads in peaks)
fripsDataFile <- "./saved_data/frips.Rdata"
# If the data file exists, load it
if (file.exists(fripsDataFile)) {
  load(fripsDataFile)
} else {
  inPeakData = c()
  # overlap with bam file to get count
  for(i in 1:nrow(design)){
      # filter MACS2 peaks data for the current libid
      peaks_ = dplyr::filter(macs2Peaks, libid == design$libid[i])
      # create GRanges object for peaks
      peaks_gr = GRanges(seqnames = peaks_$chr, IRanges(start = peaks_$start, end = peaks_$end), strand = "*")
      # get fragment counts within peaks
      fragment_counts <- chromVAR::getCounts(design$bamFile[i], peaks_gr, paired = TRUE, by_rg = FALSE, format = "bam")
      # sum fragment counts within peaks
      inPeakN = counts(fragment_counts)[,1] %>% sum
      # append in-peak count to inPeakData
      inPeakData = rbind(inPeakData, data.frame(inPeakN = inPeakN, libid = design$libid[i]))
  }
  save(inPeakData, file = pathToDataFile)
}
design = merge(design, inPeakData, by = "libid")
design = design %>% dplyr::mutate(frip = round(inPeakN/as.numeric(mapped_paired_reads) * 100,2))
table_data = dplyr::select(design, libid, donorId, `totalReads (Mio)` = tophatstats_total_reads, `align %` = pct_aligned, `aligned reads` = mapped_paired_reads, `peak calls` = nPeaks, `median peak width` = medianPeaks, FRiP = frip)
table_data$`totalReads (Mio)` = round(table_data$`totalReads (Mio)`/1e6,1)
table_data$`align %` = round(table_data$`align %`,1)
# peak counts
ggpeakN = design %>% ggplot(aes(x = responder, y = nPeaks, fill = responder)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(aes(color = donorId), position = position_jitter(0.15)) +
    scale_fill_manual(values = colors.responder) +
    scale_color_manual(values = colors.donorId) +
    theme_bw() +
    ylab("Number of peaks") +
    facet_grid(~ sort, scales = "fixed") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8), strip.text = element_text(size = 8))
plot(ggpeakN)
ggsave(filename = "./figures/peak_counts.pdf",
         plot = ggpeakN,
         width = 9,
         height = 5)
# peaks vs. reads
ggPeakNvsReads = ggplot(data = design) +
  geom_point(aes(x = tophatstats_total_reads/1e6, 
                 y = nPeaks,
                 color = donorId, 
                 shape = sort),
                 size = 1.5) + 
  scale_color_manual(values = colors.donorId) +
  labs(x = "total reads / mio", 
       y = "number of peaks", 
       color = "donor",
       shape = "cell type")+
  xlim(c(0,160)) +
  theme_bw() +
  theme(legend.position = "right") + 
  theme(legend.direction=  'vertical')
plot(ggPeakNvsReads)
ggsave(filename = "./figures/peakCalling_peakN_vs_reads.pdf",
         plot = ggPeakNvsReads,
         width = 8,
         height = 6)
# peak widths
ggPeakWidthSummarized = design  %>% ggplot(aes(x = responder, y = medianPeaks, fill = responder)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(aes(color = donorId), position = position_jitter(0.15)) +
    scale_fill_manual(values = colors.sort) +
    scale_color_manual(values = colors.donorId) +
    facet_grid(~ sort, scales = "fixed") +
    ylab("Median peak width") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8), strip.text = element_text(size = 7)) +
    coord_cartesian(ylim = c(500, 1500))
plot(ggPeakWidthSummarized)
ggsave(filename = "./figures/peak_median_widths.pdf",
         plot = ggPeakWidthSummarized,
         width = 8,
         height = 6)
ggPeakWidth = macs2Peaks %>% ggplot(aes(x = libid, y = width, fill = donorId)) +
    geom_violin() +
    facet_wrap(~ sort, scales = "free") +
    scale_fill_manual(values = colors.donorId) +
    scale_y_continuous(limits = c(100, 2000)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    ylab("Width of Peaks")
plot(ggPeakWidth)
ggsave(filename = "./figures/peakwidths_by_sample.pdf",
         plot = ggPeakWidth,
         width = 8,
         height = 6)
# FRiP
ggFRiPs = design %>% ggplot(aes(x = responder, y = frip, fill = responder)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(aes(color = donorId), position = position_jitter(0.15)) +
    scale_fill_manual(values = colors.responder) +
    scale_color_manual(values = colors.donorId) +
    theme_bw() +
    facet_grid(~ sort, scales = "free") +
    ylab("% of Fragments in Peaks") +
    xlab("")
plot(ggFRiPs)
ggsave(filename = "./figures/frips.pdf",
         plot = ggFRiPs,
         width = 8,
         height = 6)
# % MT
all_mapped_reads <- data.frame()
for (bam_file in alignmentFiles) {
  # some reads mapped to alternative chr, but less commonly
  mapped_reads <- idxstatsBam(bam_file)
  mapped_reads$file <- basename(bam_file)
  mapped_reads$libid <- paste("lib", sub(".*_lib([0-9]+)\\.bam", "\\1", mapped_reads$file), sep = "")
  all_mapped_reads <- rbind(all_mapped_reads, mapped_reads)
}
mt_reads <- all_mapped_reads %>%
  group_by(libid) %>%
  summarize(mt_reads = mapped[seqnames == "MT"]) %>%
  ungroup()
mt_reads <- mt_reads %>%
left_join(fixed_names_design, by = "libid")
old_sizes <- read_tsv("GRCh38_EBV.chrom.sizes.tsv", col_names = FALSE)
weird_chr <- all_mapped_reads %>% filter(!(seqnames %in% c(1:22, "X", "Y", "MT")))
all_chr_names <- unique(weird_chr$seqnames)
missing_chrs_df <- data.frame(X1 = all_chr_names, X2 = max(old_sizes$X2))
updated_chrom_sizes <- bind_rows(old_sizes, missing_chrs_df)
mt_reads$sort <- factor(mt_reads$sort, levels = c("DN", "non-exhausted\nCD127+", "DP CD127+", "DP PD-1+", "DP CD57+"))
mito_perc_plot <- ggplot(mt_reads, aes(x = sort, y = mt_reads/1e6, fill = sort)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(position = position_jitter(0.15)) +
    geom_line(aes(group = donorId), color = "grey", alpha = 0.25) +
    scale_fill_manual(values = viridis(5)) +
    ylab("MT reads (million)") +
    xlab("Sort") +
    theme(strip.text = element_text(size = 9), axis.text.x = element_blank())
ggsave("./figures/mt_perc.pdf", plot = mito_perc_plot, height = 8, width = 12)
# biological sex
sex_chr_reads <- data.frame()
for (bam_file in alignmentFiles) {
  reads <- idxstatsBam(bam_file) %>% dplyr::filter(seqnames %in% c("X", "Y"))
  reads$file <- basename(bam_file)
  reads$libid <- paste("lib", sub(".*_lib([0-9]+)\\.bam", "\\1", reads$file), sep = "")
  sex_chr_reads <- rbind(sex_chr_reads, reads)
}
cleaned_sex_chr_reads <- sex_chr_reads %>%
  group_by(libid) %>%
  summarize(ratio = log(mapped[seqnames == "X"] / mapped[seqnames == "Y"])) %>%
  mutate(libid = paste("lib", libid, sep = ""))
metadata_with_sex_chr_data <- read_excel("../saved_data/metadata.xlsx", sheet = 2) %>%
  select(Barcode, SiteID, PID, `Sex (Char)`) %>%
  rename(sampleBarcode = Barcode) %>%
  left_join(design, by = c("sampleBarcode", "PID", "SiteID")) %>%
  left_join(cleaned_sex_chr_reads, by = "libid") %>%
  select(libid, ratio, `Sex (Char)`) %>%
  rename(`Biological sex` = `Sex (Char)`)
metadata_with_sex_chr_data
ggplot(metadata_with_sex_chr_data, aes(x = "", y = ratio, color = `Biological sex`)) +
  geom_jitter(width = 0.2, height = 0) +
  labs(x = NULL, y = "Log ratio of reads\nmapping to X:Y chr")

```